### ISSUE TITLE
Database Path

### ISSUE THREAD

**Issue by mnookala5** [Rayeeskha/Hospital-management-system-Using-Ci4#1]
Where do we check the database tables and everything?

**Comment by Rayeeskha** [comment]
Database table alrady in souce code

**Comment by mnookala5** [comment]
Sorry I am little new to this Codeigniter. could you please describe the path where we can find the mysql tables?

**Comment by mnookala5** [comment]
Got it thanks.

**Comment by Rayeeskha** [comment]
Go to app ,config, Database.php
